projects:
  - num: 1
    basename: hello-openshift
    ifexists: delete
    tuning: default
    templates:
      - num: 1
        file: ./projects/haproxy/apps/hello-openshift/hello-openshift.json
        parameters:
         - REPLICAS: 2

  - num: 1
    basename: cakephp-mysql
    ifexists: delete
    tuning: default
    templates:
      - num: 1
        file: ./projects/haproxy/apps/cakephp-mysql/cakephp-mysql.json
        parameters:
         - REPLICAS: 2

  - num: 1
    basename: django-postgresql
    ifexists: delete
    tuning: default
    templates:
      - num: 1
        file: ./projects/haproxy/apps/django-postgresql/django-postgresql.json
        parameters:
         - REPLICAS: 2

  - num: 1
    basename: tomcat8-mongodb
    ifexists: delete
    tuning: default
    templates:
      - num: 1
        file: ./projects/haproxy/apps/tomcat8-mongodb/tomcat8-mongodb.json
        parameters:
         - REPLICAS: 2

tuningsets:
  - name: default
    pods:
      stepping:
        stepsize: 5
        pause: 0 min
      rate_limit:
        delay: 0 ms
    templates:
      stepping:
        stepsize: 5
        pause: 1 s
      rate_limit:
        delay: 5 s
