projects:
  - num: 1
    basename: centos-stress
    ifexists: delete
    tuning: default
    templates:
      - num: 1
        file: projects/haproxy/stress/stress-pod.json
        parameters: 
         - RUN: "vegeta"
         - RUN_TIME: "600"
         - GUN: "ip-172-31-42-69.us-west-2.compute.internal"

tuningsets:
  - name: default
    pods:
      stepping:
        stepsize: 5
        pause: 0 min
      rate_limit:
        delay: 0 ms

