projects:
  - num: 1
    basename: centos-stress
    ifexists: delete
    tuning: default
    templates:
      - num: 1
        file: ./projects/haproxy/stress/stress-pod.json
        parameters: 
          - RUN: "wrk"
          - RUN_TIME: "120"
#          - WRK_DELAY: "900"
          - WRK_DELAY: "0"
          - WRK_TARGETS: "."
          - WRK_KEEPALIVE: "y"
          - WRK_TLS_SESSION_REUSE: "n"

#      - num: 1
#        file: ./projects/haproxy/stress/stress-pod.json
#        parameters: 
#          - RUN: "wrk"
#          - RUN_TIME: "60"
#          - WRK_DELAY: "4000"
#          - WRK_TARGETS: "nginx-[2].router"
#          - WRK_KEEPALIVE: "y"
#          - WRK_TLS_SESSION_REUSE: "n"


tuningsets:
  - name: default
    pods:
      stepping:
        stepsize: 5
        pause: 0 min
      rate_limit:
        delay: 0 ms

